// Bundles the operator documentation into a TypeScript module so the in-app
// Guide works in the container.
//
// Reading docs/*.md from the filesystem at request time would work in local
// development and fail in production: deploy/Dockerfile.web ships only
// .next/standalone and .next/static, so the repository's docs directory does
// not exist at runtime. Generating a module at build time makes the content
// part of the bundle instead.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(here, "..");

// The docs directory sits outside apps/web locally, and is copied to the image
// root during the Docker build. Try both rather than encoding one layout.
const candidates = [
  process.env.DEVRELOS_DOCS_DIR,
  resolve(webRoot, "..", "..", "docs"),
  resolve(webRoot, "docs"),
  resolve(webRoot, "..", "docs"),
].filter(Boolean);

const docsDir = candidates.find((dir) => dir && existsSync(join(dir, "WORKFLOW.md")));
if (!docsDir) {
  console.error(
    "generate-docs: could not locate the docs directory. Looked in:\n  " +
      candidates.join("\n  ") +
      "\nSet DEVRELOS_DOCS_DIR to override."
  );
  process.exit(1);
}

// Operator-facing documents only. Architecture, product scope and the roadmap
// are for contributors and are deliberately not surfaced in the console.
const documents = [
  { slug: "workflow", file: "WORKFLOW.md", title: "Workflow Guide", blurb: "How the loops connect and what to do day to day" },
  { slug: "operator", file: "OPERATOR_GUIDE.md", title: "Operator Guide", blurb: "Per-workspace reference for every field and setting" },
  { slug: "integrations", file: "INTEGRATIONS.md", title: "Integrations", blurb: "Connectors, credentials and signal sources" },
  { slug: "running", file: "RUNNING.md", title: "Running DevRelOS", blurb: "Local development, production and tests" },
  { slug: "security", file: "SECURITY.md", title: "Security", blurb: "Trust model and the supported production boundary" },
  { slug: "mcp", file: "MCP.md", title: "Agents & MCP", blurb: "Connecting agents and IDEs to the domain API" },
];

const entries = documents.map((doc) => {
  const path = join(docsDir, doc.file);
  if (!existsSync(path)) {
    console.error(`generate-docs: ${doc.file} not found in ${docsDir}`);
    process.exit(1);
  }
  // `file` is only needed while generating; the emitted shape is GuideDoc.
  return { slug: doc.slug, title: doc.title, blurb: doc.blurb, markdown: readFileSync(path, "utf8") };
});

const outDir = join(webRoot, "lib");
mkdirSync(outDir, { recursive: true });
const outFile = join(outDir, "generated-docs.ts");

const banner = `// Generated by scripts/generate-docs.mjs from the repository docs directory.
// Do not edit. Run \`npm run docs\` to refresh, or rely on the prebuild/predev hook.

export type GuideDoc = {
  slug: string;
  title: string;
  blurb: string;
  markdown: string;
};

export const guideDocs: GuideDoc[] = ${JSON.stringify(entries, null, 2)};

export function findGuideDoc(slug: string | undefined): GuideDoc {
  return guideDocs.find((doc) => doc.slug === slug) ?? guideDocs[0];
}
`;

writeFileSync(outFile, banner, "utf8");
const bytes = entries.reduce((total, entry) => total + entry.markdown.length, 0);
console.log(`generate-docs: bundled ${entries.length} documents (${Math.round(bytes / 1024)} KB) from ${docsDir}`);
